#include<xcb/xcb.h>
#include<xcb/xcb_aux.h>
#include<xcb/xcb_keysyms.h>
#include<xcb/xcb_event.h>
#include<xcb/xcb_cursor.h>
#include<xcb/xcb_ewmh.h>
#include<xcb/xcb_icccm.h>
#include<xcb/randr.h>
#include<xcb/xinerama.h>
#include<xcb/shape.h>
